name: fluentd
home: https://github.com/teamhephy/fluentd
version: <Will be populated by the ci before publishing the chart>
description: Log shipping mechanism for Deis Workflow.
maintainers:
  - name: Deis Team
    email: engineering@deis.com
